steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'test']

timeout: '900s'
