name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 
 
      - name: Create temp .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@taskade:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: Install dependencies
        run: yarn install

      - name: Remove temp .npmrc
        run: rm .npmrc

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn run changeset:version
          title: 'chore: release'
          commit: 'chore: release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .npmrc
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@taskade:registry=https://npm.pkg.github.com/" >> .npmrc
        
      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}